Don't create folder if staging
Sage-Bionetworks/GENIE-Sponsored-Projects pull request #56
Opened 2022-02-21 08:46 UTC by thomasyu888

Fixes #30

2022-02-21 21:15 UTC, hhunterzinck requested changes
Issues
1. Line 456: File object creation fails when `self._SP_SYN_ID` is accessed because it is None.   Maybe, move this line inside the staging check?
2.  Line 1425:  The download of the metadata files will also fail because `self._SP_SYN_ID` is not defined.  Maybe this can be fixed once metadata files are produced automatically?

2022-02-22 10:43 UTC, thomasyu888 commented
That is slightly unfortunate - the metadata files are required for validation, which would sort of defeat the purpose of `--staging` if they aren't downloaded for now. hmmm.... Seems that this ticket depends on #38

2022-02-22 16:50 UTC, hhunterzinck commented
Let's pause this for now until #38 is complete.

2022-03-08 18:02 UTC, hhunterzinck approved these changes

2022-03-08 19:07 UTC, merged